name: Tests

on:
  push:
    branches-ignore:
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  download_data:
    name: Download test data
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: bash .travis/install2.sh
      - name: Upload test data
        uses: actions/upload-artifact@v1
        with:
          name: test_data
          path: test_data

  test:
    name: Test PartSeg on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: download_data
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: 3.7

    - name: Install ubuntu libraries
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0

    - name: Download test data
      uses: actions/download-artifact@v1
      with:
        name: test_data
    - shell: bash
      run: ls

    - name: Install dependencies
      run: |
        python -m pip install -r requirements/requirements_dev.txt

    - name: Test PartSeg
      run: tox -e py37-PyQt5,py37-PySide2
